name: "docker-sd-forge"

services:

  forge:
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        # Using python standalone build url. (optional)
        # - PYTHON_BUILD_URL=
        # Using forge version.
        - FORGE_COMMIT_HASH=a5ede13277b7b18e2f153c2135bab1180c310fc4
    volumes:
      # User directory.
      - ./embeddings:/home/ubuntu/forge/embeddings
      - ./extensions:/home/ubuntu/forge/extensions
      - ./models:/home/ubuntu/forge/models
      - ./outputs:/home/ubuntu/forge/outputs
      - ./webui-user.sh:/home/ubuntu/forge/webui-user.sh
      # Required packages.
      - venv:/home/ubuntu/forge/venv
      - repositories:/home/ubuntu/forge/repositories
    expose:
      - 7860
    ports:
      - 7860:7860
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # tunnel:
  #   restart: always
  #   image: cloudflare/cloudflared
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=

# Persistence.
volumes:
  venv:
  repositories:

networks:
  default:
    driver: bridge
