name: "docker-sd-forge"

services:

  forge:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        # Using python standalone build url. (optional)
        # - PYTHON_BUILD_URL=
        # Using forge version.
        - FORGE_COMMIT_HASH=a5ede13277b7b18e2f153c2135bab1180c310fc4
    volumes:
      # User directory.
      - ./embeddings:/home/ubuntu/forge/embeddings
      - ./extensions:/home/ubuntu/forge/extensions
      - ./models:/home/ubuntu/forge/models
      - ./outputs:/home/ubuntu/forge/outputs
      - ./webui-user.sh:/home/ubuntu/forge/webui-user.sh
      # Required packages.
      - venv:/home/ubuntu/forge/venv
      - repositories:/home/ubuntu/forge/repositories
    expose:
      - 7860
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: "curl http://localhost:7860/internal/ping"
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 60

  dynamic:
    image: cloudflare/cloudflared
    command: tunnel --url http://forge:7860
    networks:
      - default
    profiles:
      - dynamic
    depends_on:
      forge:
        condition: service_healthy

  static:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    profiles:
      - static
    depends_on:
      forge:
        condition: service_healthy

# Persistence.
volumes:
  venv:
  repositories:
